#!/bin/bash


# hopefully these steps will run automatically without problem, but in case the script stops somewhere, at least you know what are roughly the steps to install the dependencies
# tested on centos 7, gcc 4.8.6


mkdir -p deps
cd deps
set -e


# jellyfish


tar xf jellyfish-2.2.6.tar.gz
cd jellyfish-2.2.6
./configure --prefix=$HOME
make -j 4
make install
cd ..


# sdsl lite
# note: older versions of sdsl-lite (before Nov/8/2016) required a patch. The
# patch has been commented out in the step below, because the modification has
# been committed to the sdsl-lite repositiory
# NEED new CMAKE
git clone --recursive https://github.com/simongog/sdsl-lite.git
cd sdsl-lite
#patch  -p1 -i ../PREQ_INSTALL.sdsl-lite.patch
# Need updated cmake 
# Need g++ 4.7 above
# On uky hpc
# module load gcc/4.9.1
./install.sh
cd ..

# roaring
# note:  if the cmake step fails with this error
#   cc1: error: unrecognized command line option "-std=c11"
# Yeah, I get this error
# you probably need to change the cmake command line to this:
#   cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..

git clone https://github.com/RoaringBitmap/CRoaring.git
cd CRoaring
mkdir build
cd build
# cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME .. 
cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
make install
cd ..
cd ..


echo  "don't forget to type (or add to ~/.bashrc): "
echo  "export LD_LIBRARY_PATH=$HOME/lib:\$LD_LIBRARY_PATH"
